### ISSUE TITLE
Passwordless register failed

### ISSUE THREAD

**Issue by sipsorcery** [passwordless/passwordless-dotnet-example#1]
I get the error below when attempting this sample with `Chrome 92.0.4515.107 (64-bit)` on `Windows 10`:

````
passwordless.ts:49 DOMException: The operation either timed out or was not allowed. See: https://www.w3.org/TR/webauthn-2/#sctn-privacy-considerations-client.
register @ passwordless.ts:49
async function (async)
register @ passwordless.ts:31
RegisterPasswordless @ (index):71
async function (async)
RegisterPasswordless @ (index):65
(index):79 Things went bad Error: Passwordless register failed: The operation either timed out or was not allowed. See: https://www.w3.org/TR/webauthn-2/#sctn-privacy-considerations-client.
    at Client.register (passwordless.ts:50)
    at async HTMLButtonElement.RegisterPasswordless ((index):71)
````

I can't workout whether the 'register` has failed or not. The `create-token` API call seems to get a successful response in the Chrome debug pane.

I have a [YubiKey 5 NFC](https://www.yubico.com/ie/product/yubikey-5-nfc/) plugged in. It seems to be getting used somehow as if I take it out and click login I get the popup below:

![seckey_popup](https://user-images.githubusercontent.com/197660/128646702-de956e83-6c12-40f8-bd25-07bfda5e7093.png)

If I plug it in the popup changes to:

![seckey_popup_cantuse](https://user-images.githubusercontent.com/197660/128646707-410f05a9-5aac-4063-b0af-9668f817a8c2.png)

**Comment by abergs** [comment]
Closing this issue since v4 has been released which made several changes to the product. Please let me know if you are still experiencing any issues.
