### ISSUE TITLE
Display Name/ Nick Name

### ISSUE THREAD

**Issue by 6Hat** [passwordless/passwordless-dotnet-example#2]
First off I just wanted to say thank you for such a beautiful authentication Library! I've been following and implementing this for a while now and I am very impressed by this new version. You have refined it very well and made it drop dead simple this go round, so thank you!

I am implementing version 4 doing posting http client requests to your https://v4.passwordless.dev/ end point. For the most part this is working great.  I am pretty much following your Asp.Net C# example with the exception that I've added a couple properties that I wanted to use i.e. displayname, and nickname. However the display name and nick name are not populating either within the Bitwarden dashboard, nor when I make a list request. Any help as to what I am doing wrong would be greatly appreciated.

![image](https://github.com/passwordless/passwordless-dotnet-example/assets/32961864/5d49bf61-7dd9-4c5f-8b82-20a4a5c9b65a)

**Comment by 6Hat** [comment]
A second somewhat related question is a missing credentialId within the response of a /list request. The credentialId would be necessary to push a /delete request as seen below:
![image](https://github.com/passwordless/passwordless-dotnet-example/assets/32961864/5c4d5379-37d3-4c91-9b3d-a01ab8ac7515)

![image](https://github.com/passwordless/passwordless-dotnet-example/assets/32961864/66e62a40-4c21-4d18-8494-8863d4d11e52)

**Comment by abergs** [comment]
Hey @6Hat,
Thank you - I'm happy that you enjoy it. Thanks for your questions.
Regarding your first question, two things:

`displayname` is never stored by Passwordless. It's forwarded to the browser as part of the passkey. Some browsers show this value, while others only show the `username`. We mention this fact somewhat throughout the [docs](https://docs.passwordless.dev/guide/api.html#register-token) but it's easy to miss.

The `nickname` is actually not a property of the [/register/token](https://docs.passwordless.dev/guide/api.html#register-token) call. It's a extra argument that you can pass to the `register()`-method. This is however not well documented, except when using Typescript (https://github.com/passwordless/passwordless-client-js/blob/main/src/passwordless.ts#L35). I will keep this ticket open to make sure we're still tracking that and improve our docs. We might even consider making it part of the token payload.

Your second question;
In the `/list` call, The `credentiald` is returned but it's referred to as `descriptor.id`. While that is technically a correct term, I  agree that the terminology is confusing and we could introduce a`credentialId` property. 

Please let me know if this clarifies the situation, or if you have an other questions.

**Comment by 6Hat** [comment]
Nice, thank you for taking the time to respond. Again, I really appreciate your hard work on all of this. 

As to the Display and Nick Names... understood. Looking at the Dashboard especially gives the impression that Nickname is a passable property:
![image](https://github.com/passwordless/passwordless-dotnet-example/assets/32961864/93ddf74d-3038-4142-9de0-48aa23a9cace)

Having the ability to attach a custom name property like this I think would greatly help especially since a userId can have multiple credentials... for me, I would use it to distinguish one credential from another by passing a device name.'

As to the second point, I was thinking that descriptor.id was what was likely needed so thanks!

**Comment by abergs** [comment]
Yes that's the use case. And to make sure there is no misunderstanding, you can pass the nickname value on your client side: register(token,"my MacBook"). That will set the value in your screenshot.

**Comment by 6Hat** [comment]
That was the golden ticket! Thanks so much... I don't know how I missed that. Implemented Screenshot:
![image](https://github.com/passwordless/passwordless-dotnet-example/assets/32961864/b8e0097b-6b2f-4d99-8b0e-592904b773e6)

**Comment by 6Hat** [comment]
![image](https://github.com/passwordless/passwordless-dotnet-example/assets/32961864/0769db11-1cd6-4541-ba3d-cf8062e70017)
